spring.application.name=ledger

# Datasource (using 5433 instead of 5432 to avoid connect to local postgres)
spring.datasource.url=jdbc:postgresql://localhost:5433/ledger
spring.datasource.username=postgres
spring.datasource.password=password


# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redis_dev_pass

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false